[package]
name = "rendering"
version = "0.1.0"
edition = "2024"
publish = false
authors = ["Sam Hill <smotired@gmail.com>"]
description = "Library crate for rendering the sprite, normal map, and UI tools"

[dependencies]
anyhow = "1.0.104"
egui = "0.36.2"
pollster = "1.0.1"
vecmath = "1.0.0"
wgpu = "30.0.1"
