[package]
name = "studio"
version = "0.1.0"
edition = "2024"
publish = false
authors = ["Sam Hill <smotired@gmail.com>"]
description = "Main binary crate for the Sprite Normal Studio application"

[dependencies]
eframe = { version = "0.36.2", features = ["wgpu"] }
rfd = "0.17.2"
rendering = { path = "../rendering" }
